service_name: travis-pro
repo_token: BGkU7A5H7yEyh5e9q7bB7fD0itrNpNPqk

[![Coverage Status](https://coveralls.io/repos/github/TMentosT/git-semple/badge.svg?branch=master)](https://coveralls.io/github/TMentosT/git-semple?branch=master)
